// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbkttodkbqbjcahequrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZia3R0b2RrYnFiamNhaGVxdXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzM3MjksImV4cCI6MjA2MTQwOTcyOX0.iJhOvSJmfI8uOX9chJXsmwMlX8INboukZjeRp6RxXlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);